project:
  type: website
  output-dir: docs

website:
  title: "Harriet Goers"
  google-analytics: "G-MWQWNJ6WK8"
  navbar:
    background: "light"
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd        
      - text: Research
        href: research/index.qmd
      - text: Teaching
        href: teaching/index.qmd
    tools:
      - icon: envelope
        href: "mailto:hgoers@umd.edu"
      - icon: github
        href: https://github.com/hgoers
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

